apiVersion: apps/v1       
kind: ReplicaSet          
metadata:
  name: nginx-replicaset  
spec:
  replicas: 10             
  selector:
    matchLabels:          
      app: web
  template:               
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx       
        image: nginx:latest 
        ports:
        - containerPort: 80 
